org: jaidsondantas
app: api-estefanini
service: api-estefanini
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getAllEmployee:
    handler: employee/handlers.getAllEmployee
    events:
      - httpApi:
          path: /api/employees
          method: get
  createEmployee:
    handler: employee/handlers.createEmployee
    events:
      - httpApi:
          path: /api/employees
          method: post
          request:
            schemas:
              application/json: ${file(./employee/schemas/validate-employee.json)}
  deleteEmployee:
    handler: employee/handlers.deleteEmployee
    events:
      - httpApi:
          path: /api/employees/{id}
          method: delete
  updateEmployee:
    handler: employee/handlers.updateEmployee
    events:
      - httpApi:
          path: /api/employees/{id}
          method: put
          request:
            schemas:
              application/json: ${file(./employee/schemas/validate-employee.json)}

    api:
      handler: index.handler
      events:
        - httpApi: '*'

plugins:
  - serverless-offline
