org: jaidsondantas
app: api-estefanini
service: api-estefanini
frameworkVersion: '3'

params:
  default:
    awsKeyId: AKIA6GBMH5WJLTDOXEPJ
    awsAccessKeyId: VogIUnec7CDOhmW9g8N08nU8+tOY9TCOIH8HAPsY

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    dev:
      AWS_KEY_ID: ${param:awsKeyId},
      AWS_ACCESS_KEY: ${param:awsAccessKeyId}
    prod:
      AWS_KEY_ID: ${param:awsKeyId},
      AWS_ACCESS_KEY: ${param:awsAccessKeyId}

functions:
  getAllEmployee:
    handler: employee/handlers.getAllEmployee
    events:
      - httpApi:
          path: /api/employees
          method: get
  createEmployee:
    handler: employee/handlers.createEmployee
    events:
      - httpApi:
          path: /api/employees
          method: post
          request:
            schemas:
              application/json: ${file(./employee/schemas/validate-employee.json)}
  deleteEmployee:
    handler: employee/handlers.deleteEmployee
    events:
      - httpApi:
          path: /api/employees/{id}
          method: delete
  updateEmployee:
    handler: employee/handlers.updateEmployee
    events:
      - httpApi:
          path: /api/employees/{id}
          method: put
          request:
            schemas:
              application/json: ${file(./employee/schemas/validate-employee.json)}
plugins:
  - serverless-offline
