org: jaidsondantas
app: api-estefanini
service: api-estefanini
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
useDotenv: true

functions:
  getAllEmployee:
    handler: employee/handlers.getAllEmployee
    events:
      - httpApi:
          path: /api/employees
          method: get
          cors:
            origin: '*'
      - httpApi:
          path: /api/employees
          method: options
          cors:
            origin: '*'

  createEmployee:
    handler: employee/handlers.createEmployee
    events:
      - httpApi:
          path: /api/employees
          method: post
          request:
            schemas:
              application/json: ${file(./employee/schemas/validate-employee.json)}
          cors:
            origin: '*'

  deleteEmployee:
    handler: employee/handlers.deleteEmployee
    events:
      - httpApi:
          path: /api/employees/{id}
          method: delete
          cors:
            origin: '*'
      - httpApi:
          path: /api/employees/{id}
          method: options
          cors:
            origin: '*'


  updateEmployee:
    handler: employee/handlers.updateEmployee
    events:
      - httpApi:
          path: /api/employees/{id}
          method: put
          request:
            schemas:
              application/json: ${file(./employee/schemas/validate-employee.json)}
          cors:
            origin: '*'

plugins:
  - serverless-offline
